name: My Workflow

on:
  push:
    branches:
      - 'main'
      
jobs:
  build_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          doxyfile-path: ./docs/Doxyfile
          working-directory: ./docs
          additional-packages: font-fira-code
          
      - name: Pages Deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html/
          force_orphan: true
